import { promises as fsp } from 'fs';
import { fileURLToPath } from 'url';

export function pathify(path: string): string {
  if (path.startsWith('file://')) {
    path = fileURLToPath(path);
  }
  return path;
}

export async function instantiateEmscriptenWasm<
  T extends EmscriptenWasm.Module,
>(
  factory: EmscriptenWasm.ModuleFactory<T>,
  path: string,
  workerJS: string = '',
): Promise<T> {
  // Hand Emscripten the wasm bytes up front instead of letting its generated
  // loader find them. That loader prefers a global fetch() whenever one
  // exists, and since Node 18 ships fetch as a global it ends up calling
  // fetch('/absolute/path/to/codec.wasm'), which rejects with ERR_INVALID_URL.
  // Every fetch branch in the glue is guarded by `!wasmBinary`, so supplying
  // the bytes skips them all. This removes the old dependency on running node
  // with --no-experimental-fetch, a flag Node 22+ no longer accepts.
  const wasmBinary = await fsp.readFile(pathify(path));
  return factory({
    wasmBinary,
    locateFile(requestPath) {
      // The glue code generated by emscripten uses the original
      // file names of the worker file and the wasm binary.
      // These will have changed in the bundling process and
      // we need to inject them here.
      if (requestPath.endsWith('.wasm')) return pathify(path);
      if (requestPath.endsWith('.worker.js')) return pathify(workerJS);
      return requestPath;
    },
  });
}
